import { useEffect, useState } from 'react'
import { getScanFeedback, saveScanFeedback } from '../api/api'
import Icon from './Icon'

const Stat = ({ value, label, alert }) => <div className="rounded-xl border border-line bg-[#f8fbfa] p-3"><p className={`m-0 text-xl font-bold ${alert ? 'text-[#d14e4e]' : 'text-cyan'}`}>{value}</p><p className="mb-0 mt-1 text-[11px] font-semibold text-muted">{label}</p></div>
const categories = ['Plastic debris', 'Ghost net', 'Fishing gear', 'Metal object', 'Natural object', 'Unknown anomaly']

export default function DetectionViewer({ result, onUpdated }) {
  const [view, setView] = useState('annotated'); const [feedbackOpen, setFeedbackOpen] = useState(false)
  const [corrections, setCorrections] = useState([]); const [note, setNote] = useState(''); const [saved, setSaved] = useState(false); const [saving, setSaving] = useState(false); const [feedbackError, setFeedbackError] = useState(''); const [imageSize, setImageSize] = useState(null)
  useEffect(() => { if (!result?.scan_id) return; setFeedbackOpen(false); setSaved(false); getScanFeedback(result.scan_id).then(data => { setCorrections(data.corrections || []); setNote(data.note || '') }).catch(() => { setCorrections([]); setNote('') }) }, [result?.scan_id])
  if (!result) return <section className="panel flex min-h-[560px] flex-col"><p className="eyebrow">Scan result</p><h2 className="m-0 text-lg font-bold text-[#18383a]">Image review</h2><div className="grid flex-1 place-items-center text-center"><div><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-line bg-[#f1f8f6] text-lg font-black text-cyan">01</div><p className="mb-1 mt-4 font-semibold text-[#24484a]">Results will appear here</p><p className="m-0 text-sm text-muted">Process a sonar image to review model detections.</p></div></div></section>
  const { summary, detections } = result; const urls = { annotated: result.annotated_image_url, original: result.original_image_url, mask: result.mask_image_url }; const viewNames = { annotated: 'Live review overlay', original: 'Original', mask: 'Detection zones' }
  const correctionFor = id => corrections.find(item => item.id === String(id)) || { id: String(id), label: '', severity: '', status: 'confirmed' }
  const change = (id, key, value) => { setSaved(false); setFeedbackError(''); setCorrections(current => { const item = current.find(row => row.id === String(id)) || { id: String(id), label: '', severity: '', status: 'confirmed' }; return [...current.filter(row => row.id !== String(id)), { ...item, [key]: value }] }) }
  const corrected = detection => ({ ...detection, ...correctionFor(detection.id), label: correctionFor(detection.id).label || detection.label, severity: correctionFor(detection.id).severity || detection.severity })
  const save = async () => { setSaving(true); setFeedbackError(''); try { const response = await saveScanFeedback(result.scan_id, corrections, note); setCorrections(response.corrections || corrections); setNote(response.note || note); setSaved(true); if (response.scan) onUpdated?.(response.scan) } catch (error) { setFeedbackError(error?.response?.data?.detail || 'Feedback could not be saved. Restart the API once to enable the feedback endpoint.') } finally { setSaving(false) } }
  return <section className="panel"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">Scan result</p><h2 className="m-0 text-lg font-bold text-[#18383a]">Image review</h2></div><span className="rounded-full bg-[#e6f4ef] px-2.5 py-1 text-xs font-bold text-cyan">Processed</span></div><div className="mt-5 flex gap-2 border-b border-line pb-3">{Object.keys(urls).map(key => <button key={key} onClick={() => setView(key)} className={`rounded-lg px-3 py-1.5 text-xs font-semibold ${view === key ? 'bg-[#173f42] text-white' : 'text-muted hover:bg-[#f1f7f5]'}`}>{viewNames[key]}</button>)}</div>{view === 'annotated' ? <div className="relative mt-4 overflow-hidden rounded-xl border border-line bg-[#061c2c]"><img src={result.original_image_url} onLoad={event => setImageSize({ width: event.currentTarget.naturalWidth, height: event.currentTarget.naturalHeight })} alt="Live corrected detection overlay" className="block h-auto w-full" />{imageSize && detections.map(detection => { const item = corrected(detection); if (item.status === 'false_positive' || item.excluded) return null; const [x, y, width, height] = detection.bbox; const color = item.severity === 'high' ? '#ef4444' : item.severity === 'medium' ? '#f59e0b' : '#20b486'; return <div key={detection.id} className="pointer-events-none absolute border-2" style={{ left: `${(x / imageSize.width) * 100}%`, top: `${(y / imageSize.height) * 100}%`, width: `${(width / imageSize.width) * 100}%`, height: `${(height / imageSize.height) * 100}%`, borderColor: color }}><span className="absolute -top-5 left-0 max-w-[220px] truncate whitespace-nowrap rounded px-1.5 py-0.5 text-[9px] font-bold text-white" style={{ backgroundColor: color }}>{item.label} · {item.severity}</span></div> })}</div> : <img src={urls[view]} alt={`${viewNames[view]} sonar result`} className="mt-4 max-h-[430px] w-full rounded-xl border border-line bg-[#f6faf9] object-contain" />}
    <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><Stat value={summary.total_objects} label="Targets" /><Stat value={summary.debris_count} label="Debris signals" /><Stat value={summary.severity_counts?.high || 0} label="High priority" alert /><Stat value={`${Math.round(summary.avg_confidence * 100)}%`} label="Average confidence" /></div>
    <div className="mt-5"><div className="flex items-center justify-between"><p className="eyebrow mb-2">Detected targets</p><button onClick={() => setFeedbackOpen(value => !value)} className="flex items-center gap-1 rounded-lg bg-[#eaf5f8] px-2.5 py-1.5 text-[10px] font-bold text-[#075987]"><Icon name="settings" className="h-3.5 w-3.5" />{feedbackOpen ? 'Close correction' : 'Correct findings'}</button></div>{detections.length ? <div className="max-h-80 space-y-2 overflow-y-auto pr-1">{detections.map(detection => { const item = corrected(detection); const correction = correctionFor(detection.id); return <div key={detection.id} className={`rounded-xl border border-line bg-[#f8fbfa] px-3 py-2.5 ${item.status === 'false_positive' ? 'opacity-60' : ''}`}><div className="flex items-center justify-between gap-3"><div><p className="m-0 text-sm font-semibold text-[#24484a]">{item.label}</p><p className="mb-0 mt-1 text-[11px] text-muted">{Math.round(detection.confidence * 100)}% confidence | {detection.area_px.toLocaleString()} px²</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${item.severity === 'high' ? 'bg-rose-100 text-rose-600' : item.severity === 'medium' ? 'bg-amber-100 text-amber-700' : 'bg-emerald-100 text-emerald-700'}`}>{item.status === 'false_positive' ? 'Excluded' : item.severity}</span></div>{feedbackOpen && <div className="mt-3 grid gap-2 border-t border-line pt-3 sm:grid-cols-3"><label><span className="field-label text-[10px]">Category</span><select className="field-input py-2 text-xs" value={correction.label || detection.label} onChange={e => change(detection.id, 'label', e.target.value)}>{[detection.label, ...categories.filter(x => x !== detection.label)].map(value => <option key={value}>{value}</option>)}</select></label><label><span className="field-label text-[10px]">Priority</span><select className="field-input py-2 text-xs" value={correction.severity || detection.severity} onChange={e => change(detection.id, 'severity', e.target.value)}>{['low', 'medium', 'high'].map(value => <option key={value}>{value}</option>)}</select></label><label><span className="field-label text-[10px]">Review decision</span><select className="field-input py-2 text-xs" value={correction.status} onChange={e => change(detection.id, 'status', e.target.value)}><option value="confirmed">Confirm target</option><option value="needs_review">Needs review</option><option value="false_positive">False positive</option></select></label></div>}</div> })}</div> : <p className="text-sm text-muted">No targets met the current confidence threshold.</p>}</div>
    {feedbackOpen && <div className="mt-4 rounded-xl border border-[#b9dce6] bg-[#f2fafc] p-4"><div className="flex items-center justify-between gap-3"><p className="m-0 text-xs font-bold text-[#075987]">Analyst feedback loop</p>{saved && <span className="rounded-full bg-emerald-100 px-2 py-1 text-[9px] font-bold text-emerald-700">Saved to scan</span>}</div><p className="mb-3 mt-1 text-[10px] leading-4 text-slate-500">Edit any category, priority, or decision above. The updated values apply immediately in this review and are stored with the scan.</p><textarea value={note} onChange={e => { setNote(e.target.value); setSaved(false) }} className="field-input min-h-16 resize-y text-xs" placeholder="Optional analyst note for this review" />{feedbackError && <p role="alert" className="mb-0 mt-3 rounded-lg bg-rose-50 p-2 text-[10px] text-rose-700">{feedbackError}</p>}<button onClick={save} disabled={saving} className="action mt-3 w-full gap-2 text-xs"><Icon name="check" className="h-4 w-4" />{saving ? 'Saving feedback…' : saved ? 'Save changes' : 'Save corrections'}</button></div>}
  </section>
}
