import { useState } from 'react'
import Icon from './Icon'

const defaults = { name: 'MarineVision Operations', location: 'Indian Ocean monitoring zone', threshold: '60', alerts: true, digest: true, autoSave: true }
const readSettings = () => { try { return { ...defaults, ...JSON.parse(localStorage.getItem('marinevision_settings') || '{}') } } catch { return defaults } }

export default function Settings() {
  const [settings, setSettings] = useState(readSettings)
  const [saved, setSaved] = useState(false)
  const change = (key, value) => setSettings(current => ({ ...current, [key]: value }))
  const save = () => { localStorage.setItem('marinevision_settings', JSON.stringify(settings)); setSaved(true); setTimeout(() => setSaved(false), 2500) }
  const Toggle = ({ id, title, text }) => <div className="flex items-center justify-between gap-4 py-4"><div><p className="m-0 text-sm font-bold text-[#18383a]">{title}</p><p className="mb-0 mt-1 text-xs text-slate-500">{text}</p></div><button aria-label={title} onClick={() => change(id, !settings[id])} className={`relative h-6 w-11 rounded-full transition ${settings[id] ? 'bg-[#0b6e85]' : 'bg-slate-200'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition ${settings[id] ? 'left-6' : 'left-1'}`} /></button></div>
  return <div className="mx-auto max-w-[900px]"><div className="mb-5"><h1 className="m-0 text-2xl font-bold tracking-tight text-[#073654]">Settings</h1><p className="mb-0 mt-1 text-xs text-slate-500">Configure how MarineVision labels, reviews, and notifies your monitoring team.</p></div><div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="space-y-5"><section className="panel"><p className="eyebrow">Workspace</p><h2 className="m-0 text-lg font-bold text-[#18383a]">Survey defaults</h2><div className="mt-5 grid gap-4"><label><span className="field-label">Workspace name</span><input className="field-input" value={settings.name} onChange={e => change('name', e.target.value)} /></label><label><span className="field-label">Default survey area</span><input className="field-input" value={settings.location} onChange={e => change('location', e.target.value)} /></label><label><span className="field-label">Minimum confidence threshold <b className="float-right text-[#075987]">{settings.threshold}%</b></span><input className="w-full accent-[#0b6e85]" type="range" min="30" max="95" value={settings.threshold} onChange={e => change('threshold', e.target.value)} /></label></div></section><section className="panel"><p className="eyebrow">Workflow</p><h2 className="m-0 text-lg font-bold text-[#18383a]">Notifications & retention</h2><div className="mt-3 divide-y divide-slate-100"><Toggle id="alerts" title="High-priority alerts" text="Highlight high-severity detections during review." /><Toggle id="digest" title="Daily activity digest" text="Show a daily summary when you open the workspace." /><Toggle id="autoSave" title="Save survey metadata" text="Remember your latest survey context for the next scan." /></div></section></div><aside className="panel h-fit bg-gradient-to-b from-white to-[#f0f8fa]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#075987] text-white"><Icon name="settings" className="h-5 w-5" /></span><h2 className="mb-0 mt-4 text-base font-bold text-[#073654]">Ready for the next survey</h2><p className="mt-2 text-xs leading-5 text-slate-500">Your preferences apply on this device and help keep every scan consistent across the team.</p><button onClick={save} className="action mt-4 w-full gap-2"><Icon name="check" className="h-4 w-4" />{saved ? 'Preferences saved' : 'Save preferences'}</button><button onClick={() => setSettings(defaults)} className="mt-2 w-full rounded-lg px-3 py-2 text-xs font-bold text-slate-500 hover:bg-white">Restore defaults</button></aside></div></div>
}
